### PR TITLE
Event migration and seeds

### PR DESCRIPTION
**Pull request by aaamg**
# Description

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Change Status

- [x] Complete, tested, ready to review and merge
- [x] Complete, but not tested (may need new tests)

# How Has This Been Tested?

- [x] Added route tests
- [x] Insomnia/localhost

# Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] There are no merge conflicts

### CODE REVIEW

**Review by ethyl2 — CHANGES_REQUESTED** [review]
In data/models/models.js, the comments for locations should be fixed to say 'Location' instead of 'Event', such as in line 143.

In data/routers/publicRouter.js, I think that in line 71, the :id part of the route should be taken off. '/event' by itself should be good. We'll get the id back as part of the response.

Same thing with line 135. The post for location shouldn't need an id in the endpoint, I believe.

Other than those 2 things, looks good!

**Review by danimal-johnson — COMMENTED** [review]
Same comments as Heather: Post requests don't need an ID.
Minor change: Dubai is spelled wrong in seed file 001-events.js.

Otherwise, things are looking good.

**Comment by ethyl2** [comment]
Speaking of seeds, one field that isn't in your event seed data yet is location_id  -- to link the locations to the events.

Oh, and dj_id  as well -- to link the events to the right dj.

Also, maybe you could add the dummy data we created to your events seeds? For a few more sample events. https://github.com/Lambda-School-Labs/djhelper-fe/blob/add-event/src/data/allEvents.js

Locations, too! https://github.com/Lambda-School-Labs/djhelper-fe/blob/add-event/src/data/locations.js (just take out the location_id's in them)

**Comment by aaamg** [comment]
Should be fixed just seeding now

**Review by ethyl2 — APPROVED** [review]
I think that it looks good -- we just need to make it so the second address line isn't required. And maybe adjust the seeds.

**Pull request merged**
